/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconFa7SolidEllipsisV: typeof import('~icons/fa7-solid/ellipsis-v')['default']
    IconFaArrowDown: typeof import('~icons/fa/arrow-down')['default']
    IconFaArrowLeft: typeof import('~icons/fa/arrow-left')['default']
    IconFaArrowRight: typeof import('~icons/fa/arrow-right')['default']
    IconFaArrowUp: typeof import('~icons/fa/arrow-up')['default']
    IconFaCog: typeof import('~icons/fa/cog')['default']
    IconFaExclamationTriangle: typeof import('~icons/fa/exclamation-triangle')['default']
    IconFaHandStopO: typeof import('~icons/fa/hand-stop-o')['default']
    IconFaInfoCircle: typeof import('~icons/fa/info-circle')['default']
    IconFaListAlt: typeof import('~icons/fa/list-alt')['default']
    IconFaLock: typeof import('~icons/fa/lock')['default']
    IconFaMapMarker: typeof import('~icons/fa/map-marker')['default']
    IconFaMinus: typeof import('~icons/fa/minus')['default']
    IconFaMoonO: typeof import('~icons/fa/moon-o')['default']
    IconFaPencil: typeof import('~icons/fa/pencil')['default']
    IconFaPlus: typeof import('~icons/fa/plus')['default']
    IconFaSunO: typeof import('~icons/fa/sun-o')['default']
    IconFaTrashO: typeof import('~icons/fa/trash-o')['default']
    IconFaUnlock: typeof import('~icons/fa/unlock')['default']
    IconFaWindowMaximize: typeof import('~icons/fa/window-maximize')['default']
    IconFaWindowMinimize: typeof import('~icons/fa/window-minimize')['default']
    IconFaWrench: typeof import('~icons/fa/wrench')['default']
    IconMaterialSymbolsCloudDone: typeof import('~icons/material-symbols/cloud-done')['default']
    IconMaterialSymbolsCloudSync: typeof import('~icons/material-symbols/cloud-sync')['default']
    IconMaterialSymbolsCloudUpload: typeof import('~icons/material-symbols/cloud-upload')['default']
    IconMaterialSymbolsSync: typeof import('~icons/material-symbols/sync')['default']
    IconUilBackspace: typeof import('~icons/uil/backspace')['default']
    IconUilEnter: typeof import('~icons/uil/enter')['default']
    IconUilRedo: typeof import('~icons/uil/redo')['default']
  }
}
